name: API-Bawang-SCM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: crucial-quarter-369308
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/crucial-quarter-369308/swagger-api-image:${{ github.sha }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy API \
            --image gcr.io/crucial-quarter-369308/swagger-api-image:${{ github.sha }} \
            --platform managed \
            --region asia-southeast2-a \
            --allow-unauthenticated
